<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>El_Master.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\El-Master.Domain\El-Master.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Features\Auth\DTOs\" />
    <Folder Include="Features\Auth\Queries\" />
    <Folder Include="Features\Auth\Validators\" />
    <Folder Include="Features\Grades\Commands\" />
    <Folder Include="Features\Grades\DTOs\" />
    <Folder Include="Features\Grades\Queries\" />
    <Folder Include="Features\Courses\Commands\" />
    <Folder Include="Features\Courses\DTOs\" />
    <Folder Include="Features\Courses\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

</Project>
