<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>El_Master.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\El-Master.Domain\El-Master.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Interfaces\Repository\" />
    <Folder Include="Common\Services\" />
  </ItemGroup>

</Project>
